server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    # 기본 연결 정보
    url: jdbc:postgresql://localhost:5432/lightning_bid
    username: lightning_bid_app_user
    password: 12341234
    driver-class-name: org.postgresql.Driver
    # 커넥션 풀 상세 설정
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000

  jpa:
    hibernate:
      # create, create-drop, update, validate, none
      ddl-auto: update
    properties:
      hibernate:
        default_schema: app
        # 콘솔에 출력되는 SQL을 보기 좋게 포맷팅
        format_sql: true
        # Entity 필드(카멜케이스) -> DB 컬럼(스네이크케이스)로 자동 변환
        # 예: postTitle -> post_title
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc:
          batch_size: 20
    # 실행되는 SQL 쿼리를 콘솔에 보여줌
    show-sql: true
    open-in-view: false
