package com.lightningbid.auth.enums;

public enum TokenErrorCode {
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    TOKEN_EMPTY,
    TOKEN_FORBIDDEN,

    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_MISSING,

    SIGN_UP_TOKEN_EXPIRED,
    SIGN_UP_TOKEN_INVALID,
    SIGN_UP_TOKEN_MISSING,

    SIGN_IN_TOKEN_EXPIRED,
    SIGN_IN_TOKEN_INVALID,
    SIGN_IN_TOKEN_MISSING,
}

